doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App\Game\Tournament\Domain\Player:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Game/Tournament/Infrastructure/ORM/Mapping'
        prefix: 'App\Game\Tournament\Domain'
        alias: Game
      App\Game\Tournament\Domain\Tournament:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Game/Tournament/Infrastructure/ORM/Mapping'
        prefix: 'App\Game\Tournament\Domain'
        alias: Game
